init.time = 30

# Set to 0 for auto-detection of previous month
init.year = 0
init.month = 0

reports.scac = amtk
reports.scac.cibos = amtk.b:cibos
reports.scac.gbos = "amtk.b:gb.nec", "amtk.b:gb.me"
reports.railroadname = Amtrak

reports.mongo.batchsize = 100000
# Report metadata storage - UPDATE FOR YOUR ENVIRONMENT
reports.mongo.url = mongodb://localhost:27017
reports.mongo.database = amtk_reports
reports.mongo.collection = amtk_reports

# Message queries - UPDATE FOR YOUR ENVIRONMENT
messages.mongo.url = mongodb://localhost:27017
messages.mongo.database = amtk_reports
messages.mongo.collection = amtk_messages

aws.api.region = us-east-1
aws.s3bucket.report = rwn-amtk-report-prod
aws.s3bucket.base.url = https://s3.amazonaws.com/rwn-amtk-report-prod/
